
set(CPU_TYPE cortex-m3)

set(CPU_NAME STM32F103RC)

set(LDSCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F103RC_FLASH.ld)


list(APPEND LIBS stm32f1)
list(APPEND LIBS lwip)

list(APPEND DEFINES STM32)
list(APPEND DEFINES STM32F1)


list(APPEND INCS ${CMAKE_CURRENT_LIST_DIR})

include(${CMAKE_CURRENT_LIST_DIR}/../stm32_config.cmake)

